name: XSender
version: 1.3
main: io.github.bigcookie233.xsender.XSender
author: BigCookie233
commands:
  xsender:
    description: XSender
    usage: /xsender <server> <player>
    permission: xsender.command.xsender
    aliases: xs